# fly.toml file generated for javatagsconverter on 2024-03-10T18:12:07+01:00

app = "javatagsconverter"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"

[build]
dockerfile = "Dockerfile"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
