# fly.toml file generated for javatagsconverter on 2023-04-01T12:42:28+02:00

app = "javatagsconverter"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "cdg"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
